import torch
from safetensors import *
from typing_extensions import Self

class _TensorSlice:
    def __getitem__(self, index: slice | tuple[slice]) -> torch.Tensor: ...

    def get_shape(self) -> list[int]: ...


class safe_open:
    def __init__(self, filename: str, framework: str, device: str = 'cpu'): ...

    def keys(self) -> list[str]: ...

    def get_tensor(key: str) -> torch.Tensor: ...

    def get_slice(self, key: str) -> _TensorSlice: ...

    def __enter__(self) -> Self: ...
